Fix #198 Cast REMOTE_PORT to string
mar10/wsgidav pull request #199
Opened 2020-12-26 07:15 UTC by sinshutu

see https://github.com/mar10/wsgidav/issues/198#issuecomment-751328877

2020-12-26 13:34 UTC, mar10 commented
Thanks for tracking this down!
However, I would be prefer not to change the behavior of `safe_re_encode()` by implicitly/silently casting int to string.

What do you think about fixing it here:
```py
            for k, v in environ.items():
                if k == k.upper():
                    _logger.info("{:<20}: '{}'".format(k, safe_re_encode(v, "utf8")))
```
I have forgotten why the test for `k == k.upper()` was in, I guess we can drop it. Having the same key in different caps seems suspicious and should be debuggable.
We could also add some safety, to catch encoding errors, e.g. (untestet)
```py
            for k, v in environ.items():
                try:
                    v = safe_re_encode(v, "utf8")
                except Exception:
                    pass
                _logger.info("{:<20}: {!r}".format(k, v))
```
or similar.
(As a bonus, sorting the list by header name would be a plus.)

2020-12-27 08:09 UTC, sinshutu commented
@mar10  Thankyou for response.
I fix it a little more considering the above idea.

2020-12-27 08:34 UTC, mar10 commented
FYI i merged an unrelated fix for the failing tests into yout PR

2020-12-27 09:58 UTC, sinshutu commented
@mar10 

`safe_re_encoding` must take a value with an `.encode` implementation as an argument.
So what about the following changes?
```python
    if not encoding_to:
        encoding_to = "ASCII"
    if compat.is_bytes(s):
        s = s.decode(encoding_to, errors=errors).encode(encoding_to)
    elif hasattr(s, 'encode'):
        s = s.encode(encoding_to, errors=errors).decode(encoding_to)
    else:
        raise TypeError
    return s
```

Also, since the value of environ is not guaranteed to be a string(have .encode), the process of casting to str is the responsibility of the caller, so it is likely to be implemented like this.

```python
    for k, v in environ.items():
        _logger.info("{:<20}: '{}'".format(k, safe_re_encode(str(v), "utf8")))
```

2020-12-27 13:37 UTC, mar10 requested changes

2020-12-27 13:37 UTC, mar10 commented on wsgidav/util.py
> +    elif hasattr(s, "encode"):
This method should not implement permissive fallbacks. It is up to the caller to pass in valid arguments.

2020-12-27 13:37 UTC, mar10 commented on wsgidav/debug_filter.py
> +                _logger.info("{:<20}: '{}'".format(k, safe_re_encode(str(v), "utf8")))
I think `str(v)` may raise an encoding exception, so we should handle it with try/except. See the proposed implementation in the PR comments instead

2020-12-29 16:44 UTC, sinshutu commented
@mar10 
Stopped making changes to safe_re_encode and added try / catch.
I couldn't think of what to implement in the except block, so please add it if necessary.

2020-12-30 12:49 UTC, mar10 approved these changes

2020-12-30 12:49 UTC, merged